<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MapLootEditorLite.Server</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <Version>2.1.0</Version>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AssemblyName>MapEditorLite.Server</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.0" />
    <PackageReference Include="WTT-ServerCommonLib" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="package.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
